import assert from 'node:assert/strict';
import {test} from 'node:test';
import {SAMPLE,summarize,reconciled,mergeStatements,minor} from '../lib/finance';
import {researchRequest,buildQuery,parseResearch} from '../lib/research';
import {healthMetrics,SAMPLE_PROFILE} from '../lib/health';
import {fromSheetValues} from '../lib/sheets';
test('cash, debt, transfers and repayments remain distinct',()=>{const s=summarize(SAMPLE,'2026-08');assert.equal(s.cash,1842065);assert.equal(s.debt,248000);assert.equal(s.net,472000);assert.equal(s.spending,422000);assert.equal(s.cash!-600000-248000,994065);assert.ok(SAMPLE.every(reconciled));});
test('a missing period is unavailable and an invalid statement cannot contribute cash',()=>{assert.equal(summarize(SAMPLE,'2026-07').complete,false);const bad={...SAMPLE[0],closing:1};const s=summarize([bad],'2026-08');assert.equal(s.cash,null);assert.equal(s.accepted.length,0);});
test('repeated import is idempotent and conflicting revisions require review',()=>{assert.equal(mergeStatements(SAMPLE,SAMPLE).length,3);assert.throws(()=>mergeStatements(SAMPLE,[{...SAMPLE[0],closing:100}]));assert.equal(minor('10.01'),1001);assert.throws(()=>minor('10.001'));});
test('public research schema rejects private fields',()=>{const r={metric:'net_worth',region:'MY',band:'positive',confirmed:true};assert.ok(researchRequest.safeParse(r).success);assert.equal(researchRequest.safeParse({...r,amount:1000}).success,false);assert.equal(researchRequest.safeParse({...r,confirmed:false}).success,false);const valid=researchRequest.parse(r);assert.ok(!buildQuery(valid).includes('1000'));const cards=parseResearch('Title: Deposit eligibility\nURL: https://www.pidm.gov.my/general/faqs/deposit-insurance-system\nPublished: N/A\nHighlights: Eligible deposits are protected.\n\nTitle: Untrusted\nURL: https://evil.example\nHighlights: Buy now.',valid);assert.equal(cards.length,1);assert.equal(cards[0].published,null);});
test('Google Sheets numerical MYR converts exactly and validates joins',()=>{const sh=['statement_id','bank','account','type','currency','period','as_of','opening_balance','closing_balance','transaction_coverage'];const th=['statement_id','transaction_id','date','description','amount','kind','category'];const statements=[sh,['s1','Bank','Savings •1234','deposit','MYR','2026-08','2026-08-31',10,20.01,true]];const transactions=[th,['s1','t1','2026-08-02','Income',10.01,'income','Income']];const data=fromSheetValues(statements,transactions);assert.equal(data[0].closing,2001);assert.equal(reconciled(data[0]),true);assert.throws(()=>fromSheetValues(statements,[th,['missing','t1','2026-08-02','Income',10.01,'income','Income']]));assert.throws(()=>fromSheetValues([...statements,statements[1]],transactions));});

test("missing known account invalidates period completeness",()=>{const older={...SAMPLE[1],period:"2026-07",asOf:"2026-07-31",transactions:[],transactionCoverage:false};const summary=summarize([SAMPLE[0],older],"2026-08");assert.equal(summary.missingAccounts,1);assert.equal(summary.complete,false);});

test('three health metrics use complete assets, liabilities, gross income and new contributions',()=>{const h=healthMetrics(SAMPLE,'2026-08',SAMPLE_PROFILE);assert.equal(h.netWorth,4794065);assert.ok(Math.abs(h.dti!-13.24)<1e-10);assert.equal(h.savings,20);assert.equal(h.dtiBand,'flexible');assert.equal(h.savingsBand,'on_target');});
test('zero income, unconfirmed profile and different months do not fabricate ratios',()=>{assert.equal(healthMetrics(SAMPLE,'2026-08',{...SAMPLE_PROFILE,grossIncome:0}).dti,null);assert.equal(healthMetrics(SAMPLE,'2026-08',{...SAMPLE_PROFILE,confirmed:false}).netWorth,null);assert.equal(healthMetrics(SAMPLE,'2026-07',SAMPLE_PROFILE).savings,null);});
test('target boundaries use below 20, below 36 and at least 20',()=>{assert.equal(healthMetrics(SAMPLE,'2026-08',{...SAMPLE_PROFILE,debtPayments:200000}).dtiBand,'within_target');assert.equal(healthMetrics(SAMPLE,'2026-08',{...SAMPLE_PROFILE,debtPayments:360000}).dtiBand,'high');assert.equal(healthMetrics(SAMPLE,'2026-08',{...SAMPLE_PROFILE,savingsContributions:199900}).savingsBand,'below_target');assert.equal(researchRequest.safeParse({metric:'dti',region:'MY',band:'high',confirmed:true,dti:45}).success,false);assert.equal(researchRequest.safeParse({metric:'dti',region:'MY',band:'positive',confirmed:true}).success,false);});
