import {researchRequest,buildQuery,parseSearchResults,isSelectedArticle,parseFetchedArticle,primaryHosts,ResearchCard} from '@/lib/research';
async function mcp(name:string,args:Record<string,unknown>){const response=await fetch('https://mcp.exa.ai/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify({jsonrpc:'2.0',id:crypto.randomUUID(),method:'tools/call',params:{name,arguments:args}}),signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('provider');const raw=await response.text();let data;try{data=JSON.parse(raw);}catch{data=raw.split('\n').filter(l=>l.startsWith('data: ')).map(l=>JSON.parse(l.slice(6))).find(d=>d.result||d.error);}if(data?.error||data?.result?.isError)throw new Error('provider');return (data?.result?.content||[]).filter((c:{type:string})=>c.type==='text').map((c:{text:string})=>c.text).join('\n') as string;}
export async function POST(request:Request){
 const headers={'Cache-Control':'no-store'};
 if(request.headers.get('origin')&&new URL(request.headers.get('origin')!).host!==new URL(request.url).host)return Response.json({error:'Use research from your Arus workspace.'},{status:403,headers});
 let input;try{const raw=await request.text();if(raw.length>2048)throw new Error();input=researchRequest.parse(JSON.parse(raw));}catch{return Response.json({error:'Confirm the metric inputs first. Only a supported metric, general topic and geography are accepted; private amounts and ratios are rejected.'},{status:422,headers});}
 if(input.region!=='MY')return Response.json({cards:[],message:'The selected Mr Money TV corpus focuses on Malaysia. Choose Malaysia; its articles do not establish rules or eligibility for other countries.'},{headers});
 try{let cards:ResearchCard[]=[],provider;const key=process.env.EXA_API_KEY;if(key){const response=await fetch('https://api.exa.ai/search',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':key},body:JSON.stringify({query:buildQuery(input),type:'auto',numResults:5,includeDomains:primaryHosts,contents:{text:{maxCharacters:12000}}}),signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('provider');const data=await response.json() as {results?:Parameters<typeof parseSearchResults>[0]};cards=parseSearchResults(data.results||[],input);provider='Exa Search API';}else{const search=await mcp('web_search_exa',{query:buildQuery(input),objective:'Find relevant personal finance articles exclusively on mrmoneytv.com/articles/. Return specific article URLs; avoid indexes. These are editorial research sources, not authoritative regulatory advice.',numResults:5});const urls=[...new Set([...search.matchAll(/^URL:\s*(https:\/\/\S+)/gm)].map(m=>m[1]).filter(isSelectedArticle))].slice(0,3);const fetched=await Promise.allSettled(urls.map(async url=>parseFetchedArticle(await mcp('web_fetch_exa',{urls:[url],maxCharacters:12000}),input)));cards=fetched.flatMap(r=>r.status==='fulfilled'&&r.value?[r.value]:[]);provider='Exa MCP · search + article retrieval';}return Response.json({cards,query:buildQuery(input),provider,message:cards.length?'Mr Money TV article evidence retrieved. Review prompts are Arus’s interpretation. Publication dates may be older than retrieval dates; verify current product terms with the provider.':'No matching article evidence could be retrieved. Try another metric. No suggestion was invented.'},{headers});
 }catch{return Response.json({error:'Exa is unavailable or took too long. Your financial data is unchanged. Try again shortly.'},{status:502,headers});}
}
