import {researchRequest} from '@/lib/research';
import {agentApi,agentRequest,agentCards} from '@/lib/exa-agent';
const headers={'Cache-Control':'no-store'};
const encoder=new TextEncoder();
async function signingKey(key:string){return crypto.subtle.importKey('raw',encoder.encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
async function ticket(key:string,data:unknown){const payload=btoa(JSON.stringify(data));const sig=await crypto.subtle.sign('HMAC',await signingKey(key),encoder.encode(payload));return payload+'.'+btoa(String.fromCharCode(...new Uint8Array(sig)));}
async function readTicket(key:string,value:string){const [payload,sig]=value.split('.');if(!payload||!sig||!await crypto.subtle.verify('HMAC',await signingKey(key),Uint8Array.from(atob(sig),c=>c.charCodeAt(0)),encoder.encode(payload)))throw new Error();const data=JSON.parse(atob(payload));if(data.expires<Date.now()||!/^agent_run_[A-Za-z0-9_.:-]+$/.test(data.id))throw new Error();return {...data,input:researchRequest.parse(data.input)};}
export async function POST(request:Request){
 if(request.headers.get('origin')&&new URL(request.headers.get('origin')!).host!==new URL(request.url).host)return Response.json({error:'Use research from your Arus workspace.'},{status:403,headers});
 const key=process.env.EXA_API_KEY;if(!key)return Response.json({error:'Configure the server-side EXA_API_KEY to use Exa Agent.'},{status:503,headers});
 let input;try{const raw=await request.text();if(raw.length>2048)throw new Error();input=researchRequest.parse(JSON.parse(raw));}catch{return Response.json({error:'Confirm your metric inputs. Private amounts and unsupported fields are not accepted.'},{status:422,headers});}
 if(input.region!=='MY')return Response.json({cards:[],message:'The selected articles cover Malaysia. Choose Malaysia to research this corpus.'},{headers});
 try{const run=await agentApi(key,'',agentRequest(input));if(!run.id||!['queued','running','completed'].includes(run.status))throw new Error('Exa Agent did not start successfully.');return Response.json({status:'running',ticket:await ticket(key,{id:run.id,input,expires:Date.now()+3600000}),cards:[],message:'Exa Agent is reading articles and developing your action plan.'},{status:202,headers});}catch(e){return Response.json({error:e instanceof Error?e.message:'Research could not start.'},{status:502,headers});}
}
export async function GET(request:Request){const key=process.env.EXA_API_KEY;if(!key)return Response.json({error:'Exa is not configured.'},{status:503,headers});let data;try{data=await readTicket(key,new URL(request.url).searchParams.get('ticket')||'');}catch{return Response.json({error:'Research session expired. Start a new research request.'},{status:403,headers});}
 try{const run=await agentApi(key,'/'+encodeURIComponent(data.id));if(run.status==='queued'||run.status==='running')return Response.json({status:run.status},{status:202,headers});if(run.status!=='completed')throw new Error('Exa Agent ended without a completed answer. Try again.');const cards=agentCards(run,data.input);return Response.json({status:'completed',cards,provider:'Exa Agent',message:cards.length?'Exa Agent generated this review plan from Mr Money TV articles. It reflects your metric status at search time; refresh after changing financial inputs.':'Exa Agent did not return sufficiently grounded advice from the selected articles. No unsupported recommendation is shown.'},{headers});}catch(e){return Response.json({error:e instanceof Error?e.message:'Research could not finish.'},{status:502,headers});}}
