'use client';
import {useMemo,useState} from 'react';
import {ArrowUpRight,ArrowDownLeft,ArrowRight,Plus,ShieldCheck,FileText,ChevronRight,Search,Check,RefreshCw,X,Download,Wallet,SlidersHorizontal,Info,Leaf,Globe2,Bookmark} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {ChartContainer} from '@/components/ui/chart';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {SAMPLE,Statement,summarize,money,minor,reconciled} from '@/lib/finance';
import {metrics,regions,ResearchRequest,ResearchCard,buildQuery} from '@/lib/research';
import {healthMetrics,Profile,SAMPLE_PROFILE,blankProfile} from '@/lib/health';
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:Record<string,string>;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{Object.entries(items).map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>;}
const monthLabel=(s:string)=>new Date(s+'-01T12:00:00').toLocaleDateString('en-MY',{month:'long',year:'numeric'});
const dateLabel=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('en-MY',{day:'numeric',month:'short',year:'numeric'});
export default function Home(){
 const [statements,setStatements]=useState<Statement[]>(SAMPLE),[sample,setSample]=useState(true),[period,setPeriod]=useState('2026-08'),[tab,setTab]=useState('overview'),[modal,setModal]=useState(''),[notice,setNotice]=useState('');
 const [profile,setProfile]=useState<Profile>(SAMPLE_PROFILE),[metric,setMetric]=useState<ResearchRequest['metric']>('net_worth'),[region,setRegion]=useState<ResearchRequest['region']>('MY');
 const [profileDraft,setProfileDraft]=useState<Record<string,string>>({}),[profileDate,setProfileDate]=useState('2026-08-31'),[profileConfirmed,setProfileConfirmed]=useState(false),[profileError,setProfileError]=useState('');
 const [research,setResearch]=useState<ResearchCard[]>([]),[researching,setResearching]=useState(false),[researchMessage,setResearchMessage]=useState(''),[saved,setSaved]=useState<string[]>([]);
 const [sheetUrl,setSheetUrl]=useState(''),[syncing,setSyncing]=useState(false),[syncError,setSyncError]=useState(''),[syncedAt,setSyncedAt]=useState('');
 const s=useMemo(()=>summarize(statements,period),[statements,period]);
 const periods=Object.fromEntries([...new Set(['2026-08','2026-07',...statements.map(s=>s.period)])].sort().reverse().map(p=>[p,monthLabel(p)]));
 const health=useMemo(()=>healthMetrics(statements,period,profile),[statements,period,profile]);
 const selectedBand=metric==='net_worth'?health.netBand:metric==='dti'?health.dtiBand:health.savingsBand;
 const request:ResearchRequest|null=selectedBand==='unknown'?null:{metric,region,band:selectedBand as ResearchRequest['band'],confirmed:true};
 const percent=(n:number|null)=>n===null?'—':`${n.toFixed(1)}%`;
 const metricValue=metric==='net_worth'?(health.netWorth===null?'Needs confirmation':`RM ${money(health.netWorth)}`):percent(metric==='dti'?health.dti:health.savings);
 function openProfile(){setProfileDraft(Object.fromEntries(['otherAssets','otherLiabilities','grossIncome','debtPayments','savingsContributions'].map(k=>[k,String((profile[k as keyof Profile] as number)/100)])));setProfileDate(profile.asOf||period+'-01');setProfileConfirmed(profile.confirmed&&profile.period===period);setProfileError('');setModal('profile');}
 function saveProfile(){try{if(!profileConfirmed)throw new Error('Confirm the amounts and coverage first.');if(!profileDate.startsWith(period)||new Date(profileDate).toISOString().slice(0,10)!==profileDate)throw new Error('Choose a valid valuation date in the selected month.');const values=Object.fromEntries(Object.entries(profileDraft).map(([k,v])=>[k,minor(v)]));setProfile({...profile,...values,period,asOf:profileDate,confirmed:true});closeModal();setNotice('Financial inputs confirmed. The three metrics have been recalculated.');}catch(e){setProfileError(e instanceof Error?e.message:'Check the inputs.');}}
 function closeModal(){setModal('');setSyncError('');}
 function toggleSample(){setStatements(sample?[]:SAMPLE);setProfile(sample?blankProfile:SAMPLE_PROFILE);setSample(!sample);setSyncedAt('');setResearch([]);setNotice(sample?'Your workspace is empty. Connect Google Sheets to begin.':'Illustrative data loaded.');}
 async function syncSheet(){setSyncing(true);setSyncError('');try{const response=await fetch('/api/sheets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:sheetUrl})});const data=await response.json() as {error?:string;statements:Statement[];retrievedAt:string};if(!response.ok)throw new Error(data.error);setStatements(data.statements);setSample(false);setPeriod(data.statements.map((s:Statement)=>s.period).sort().at(-1)||period);setSyncedAt(data.retrievedAt);setProfile(sample?blankProfile:{...profile,confirmed:false});setNotice('Google Sheets refreshed. Confirm financial inputs against the updated balances.');closeModal();}catch(e){setSyncError(e instanceof Error?e.message:'The sheet could not be read.');}finally{setSyncing(false);}}
 async function runResearch(){if(!request){openProfile();return;}setResearching(true);setResearchMessage('');try{const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});const data=await response.json() as {error?:string;cards:ResearchCard[];message?:string};if(!response.ok)throw new Error(data.error);setResearch(data.cards);setResearchMessage(data.message||'Primary sources retrieved. Check the evidence and dates before acting.');}catch(e){setResearchMessage(e instanceof Error?e.message:'Research could not be completed.');}finally{setResearching(false);}}
 function exportCsv(){const escape=(v:unknown)=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv=[['Date','Description','Account','Kind','Category','Signed amount MYR','Source','Page'],...s.tx.map(t=>[t.date,t.description,t.statement.account,t.kind,t.category,(t.amount/100).toFixed(2),t.statement.sourceName,t.page])].map(row=>row.map(escape).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`arus-${period}.csv`;a.click();URL.revokeObjectURL(url);}
 return <div className="app-shell"><header className="appbar"><a href="/" className="brand"><span className="brand-symbol">≈</span> arus<span className="brand-divider"/><span className="brand-caption">A little more clarity.</span></a><span className="private-label"><ShieldCheck size={15}/> Private workspace</span></header>
 <main><section className="page-heading"><div><p className="eyebrow">YOUR FINANCIAL WORKSPACE</p><h1>Your money, together.</h1><p className="muted">One considered view of your statements, spending and next steps.</p></div><Button className="primary" onClick={()=>setModal('sheets')}><RefreshCw size={16}/> {syncedAt?'Refresh Google Sheets':'Connect Google Sheets'}</Button></section>
 <div className="sample-banner"><span><span className="status-dot"/>{sample?<><strong>Sample workspace</strong> · Illustrative data, not your bank statement.</>:<><strong>Your Google Sheets ledger</strong> · Loaded data clears on reload.</>}</span><button onClick={toggleSample}>{sample?'Start with my data':'Load sample data'} <ArrowRight size={14}/></button></div>
 {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={15}/></button></div>}
 <Tabs value={tab} onValueChange={setTab}><div className="tabline"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="transactions">Transactions</TabsTrigger><TabsTrigger value="research">Insights & research</TabsTrigger></TabsList><button className="text-button" onClick={()=>setModal('coverage')}><FileText size={14}/> Statement coverage <ChevronRight size={14}/></button></div>
 <TabsContent value="overview"><div className="section-title metric-heading"><div><h2>Your financial health</h2><p className="muted">Three measures. One consolidated picture.</p></div><div className="inline-actions"><Choice value={period} onChange={setPeriod} items={periods} label="Metric reporting period"/><Button variant="outline" onClick={openProfile}><SlidersHorizontal size={15}/> Review inputs</Button></div></div><div className="balance-grid">
 <article className="balance-card cash"><div className="card-label"><span>Net worth</span><Wallet size={19}/></div><div className="amount"><span>RM</span> {money(health.netWorth)}</div><p>Total assets − total liabilities</p><div className="metric-status">{health.netWorth===null?'Needs confirmation':health.netWorth>0?'Positive net worth':'Liabilities meet or exceed assets'}</div><div className="metric-detail"><span>Assets <strong>RM {money(health.netWorth===null?null:health.totalAssets)}</strong></span><span>Liabilities <strong>RM {money(health.netWorth===null?null:health.totalLiabilities)}</strong></span></div><button className="card-foot" onClick={()=>{setMetric('net_worth');setTab('research');}}>Target: positive & trending upward <ArrowRight size={14}/></button></article>
 <article className="balance-card"><div className="card-label"><span>Debt-to-income</span><span className="pill">Monthly</span></div><div className="amount">{percent(health.dti)}</div><p>Debt payments ÷ gross income</p><div className="metric-status">{health.dti===null?'Needs gross income & debt payments':health.dti<20?'High flexibility':health.dti<36?'Within your target':'Above your target'}</div><meter className="metric-meter" min={0} max={100} value={Math.min(health.dti||0,100)} aria-label="Debt-to-income percentage"/><div className="meter-labels"><span>0%</span><span>50%</span><span>100%</span></div><button className="card-foot link-foot" onClick={()=>{setMetric('dti');setTab('research');}}>Target: below 36% · ideally below 20% <ArrowRight size={14}/></button></article>
 <article className="balance-card"><div className="card-label"><span>Savings rate</span><span className="pill">Monthly</span></div><div className="amount">{percent(health.savings)}</div><p>New savings & investments ÷ gross income</p><div className="metric-status">{health.savings===null?'Needs confirmed contributions & income':health.savings>=20?'Meeting your savings target':'Room to grow your savings'}</div><meter className="metric-meter" min={0} max={100} value={Math.min(health.savings||0,100)} aria-label="Savings rate percentage"/><div className="meter-labels"><span>0%</span><span>50%</span><span>100%</span></div><button className="card-foot link-foot" onClick={()=>{setMetric('savings');setTab('research');}}>Target: at least 20% of gross income <ArrowRight size={14}/></button></article></div>
 <p className="context-note"><Info size={14}/><span>{health.dates.length>1?`Mixed valuation dates: ${dateLabel(health.dates[0])}–${dateLabel(health.dates.at(-1)!)}. `:health.dates.length?`As of ${dateLabel(health.dates[0])}. `:''}Targets are your planning benchmarks. A single snapshot cannot establish an upward trend. Gross income is not inferred from salary deposits.</span></p>
 <div className="section-title"><div><h2>The month in perspective</h2><p className="muted">Money movements across included accounts.</p></div><Choice value={period} onChange={setPeriod} items={periods} label="Reporting period"/></div>
 {!s.complete&&<div className="coverage-warning"><Info size={17}/><div><strong>{s.current.length?'Transaction coverage incomplete':'Missing period'}</strong><p>{s.current.length?`${s.missingAccounts} known account(s) missing this period; ${s.current.length-s.accepted.length} statement(s) have unverified or unreconciled transactions. Totals include only reconciled statements.`:`No statements for ${monthLabel(period)}. Missing data is not treated as zero.`}</p></div><button onClick={()=>setModal('coverage')}>Review coverage <ArrowRight size={14}/></button></div>}
 <div className="analysis-grid"><article className="panel"><div className="panel-heading"><div><h3>Cash flow</h3><p>External movements through deposit accounts</p></div><span className="pill">{s.complete?'Included statements':'Partial coverage'}</span></div><div className="flow-numbers"><div><span><ArrowDownLeft size={14}/> Money in</span><strong>RM {money(s.accepted.some(a=>a.type==='deposit')?s.income:null)}</strong></div><div><span><ArrowUpRight size={14}/> Money out</span><strong>RM {money(s.accepted.some(a=>a.type==='deposit')?s.outflow:null)}</strong></div><div><span>Net cash flow</span><strong className="green">RM {money(s.accepted.some(a=>a.type==='deposit')?s.net:null)}</strong></div></div>
 {s.accepted.some(a=>a.type==='deposit')?<ChartContainer config={{income:{label:'Money in',color:'#1e6454'},outflow:{label:'Money out',color:'#c6d9d0'}}} className="flow-chart"><BarChart accessibilityLayer data={s.weeks} barGap={5}><CartesianGrid vertical={false} stroke="#edf0ea"/><XAxis dataKey="name" axisLine={false} tickLine={false} tickMargin={10}/><YAxis axisLine={false} tickLine={false} width={42} tickFormatter={n=>n>=1000?`${n/1000}k`:n}/><Tooltip formatter={v=>`RM ${Number(v).toLocaleString('en-MY')}`}/><Bar dataKey="income" name="Money in" fill="#1e6454" radius={[4,4,0,0]} maxBarSize={25}/><Bar dataKey="outflow" name="Money out" fill="#c6d9d0" radius={[4,4,0,0]} maxBarSize={25}/></BarChart></ChartContainer>:<div className="empty-chart"><FileText/><p>A reconciled deposit ledger will bring this chart to life.</p></div>}
 <div className="chart-caption"><span><i className="legend dark"/> Money in <i className="legend light"/> Money out</span><span>Day of month</span></div><p className="fine">Own-account transfers excluded. Card repayments count as cash outflow, not new purchases.</p></article>
 <article className="panel"><div className="panel-heading"><div><h3>Purchase spending</h3><p>Recognized purchases across deposits & cards</p></div><span className="small-icon"><ArrowUpRight size={18}/></span></div><div className="spend-total">RM {money(s.accepted.length?s.spending:null)}</div><div className="categories">{s.categories.length?s.categories.map((c,i)=><div className="category" key={c.name}><div><span><i style={{background:['#286652','#47816c','#729985','#91b2a0','#b0c4b7','#cad8cf'][i%6]}}/>{c.name}</span><strong>RM {money(c.value)}</strong></div><meter min={0} max={s.spending} value={c.value} aria-label={`${c.name} spending`}/></div>):<div className="empty-chart"><p>No recognized purchases for this period.</p></div>}</div><p className="fine">Transfers and card repayments excluded. Refunds reported separately: RM {money(s.accepted.length?s.refunds:null)}.</p></article></div>
 <div className="bottom-grid"><article className="panel"><div className="panel-heading"><div><h3>Your reported accounts</h3><p>Each balance keeps its own statement date</p></div><button className="text-button" onClick={()=>setModal('coverage')}>View all <ArrowRight size={14}/></button></div>{s.latest.length?s.latest.map(a=><div className="account-row" key={a.id}><span className="bank-avatar">{a.bank.split(' ').map(w=>w[0]).slice(0,2).join('')}</span><div><strong>{a.bank}</strong><p>{a.account} · {dateLabel(a.asOf)}</p></div><div className="account-value"><strong>RM {money(a.closing)}</strong><p>{a.type==='card'?'Card liability':'Deposit'}{a.transactionCoverage&&!reconciled(a)?' · Unreconciled':''}</p></div></div>):<p className="empty-text">Connect Google Sheets to see your accounts here.</p>}</article>
 <article className="research-teaser"><span className="leaf-icon"><Leaf size={22}/></span><p className="eyebrow">A MORE INFORMED NEXT STEP</p><h2>A little context.<br/>A clearer perspective.</h2><p>Explore practical guidance shaped by your net worth, debt burden and savings rate, with every source in view.</p><Button variant="outline" onClick={()=>setTab('research')}>Explore insights <ArrowRight size={16}/></Button><span className="fine">Powered by Exa · You stay in control</span></article></div>{research.length>0&&<section><div className="section-title"><div><h2>Guidance from your metrics</h2><p className="muted">Public research for the metric status at search time. Refresh research after changing inputs.</p></div><button className="text-button" onClick={()=>setTab('research')}>View evidence & dates <ArrowRight size={14}/></button></div><div className="question-grid">{research.slice(0,3).map(c=><article className="research-card" key={c.url}><span className="pill">{c.holding}</span><h3 style={{marginTop:12}}>A point to review</h3><p className="fine" style={{marginTop:12}}>{c.suggestion}</p><a className="text-button" style={{marginTop:15,whiteSpace:'normal'}} href={c.url} target="_blank" rel="noopener noreferrer">{c.title} <ArrowUpRight size={14}/></a><p className="fine" style={{marginTop:8}}>Retrieved {new Date(c.retrieved).toLocaleDateString('en-MY')}</p></article>)}</div></section>}</TabsContent>
 <TabsContent value="transactions"><div className="section-title"><div><h2>A ledger you can trace</h2><p className="muted">Reconciled entries only. Card charges increase debt; deposit debits reduce cash.</p></div><div className="inline-actions"><Choice value={period} onChange={setPeriod} items={periods} label="Transaction period"/><Button variant="outline" disabled={!s.tx.length} onClick={exportCsv}><Download size={15}/> Export CSV</Button></div></div><article className="panel ledger"><Table><TableHeader><TableRow>{['Date','Transaction / source','Account','Type','Category','Signed RM'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{s.tx.map(t=><TableRow key={t.statement.id+t.id}><TableCell>{t.date.slice(5)}</TableCell><TableCell><strong>{t.description}</strong><span className="table-meta">{t.sourceRow?`Google Sheets · Transactions row ${t.sourceRow}`:`${t.statement.sourceName} · p. ${t.page}`}</span></TableCell><TableCell>{t.statement.account}</TableCell><TableCell><span className="pill">{t.kind}</span></TableCell><TableCell>{t.category}</TableCell><TableCell className="numeric">{money(t.amount)}</TableCell></TableRow>)}</TableBody></Table>{!s.tx.length&&<p className="empty-text">No reconciled transactions for {monthLabel(period)}. Refresh Google Sheets or review statement coverage.</p>}</article></TabsContent>
 <TabsContent value="research"><div className="section-title"><div><p className="eyebrow">RESEARCH, WITH CONTEXT</p><h2>Understand your numbers. Explore your next step.</h2><p className="muted">Exa finds public guidance based on the status of your three financial metrics.</p></div><Button variant="outline" onClick={openProfile}><SlidersHorizontal size={15}/> Review metric inputs</Button></div><div className="research-toolbar"><div className="holding-summary"><span className="small-icon"><Wallet size={20}/></span><div><strong>{metrics[metric]} · {metricValue}</strong><p>{monthLabel(period)} · {request?'Research uses a general topic derived from this metric.':'Confirm the missing inputs before researching this metric.'}</p></div>{request&&<span className="pill"><Check size={12}/> Inputs confirmed</span>}</div><div className="inline-actions"><Choice value={metric} onChange={v=>setMetric(v as ResearchRequest['metric'])} items={metrics} label="Research metric"/><Choice value={region} onChange={v=>setRegion(v as ResearchRequest['region'])} items={regions} label="Research geography"/><Button className="primary" onClick={runResearch} disabled={researching}>{researching?<RefreshCw className="spin" size={15}/>:<Search size={15}/>} {researching?'Researching…':'Research guidance with Exa'}</Button></div></div><details className="query-disclosure"><summary><ShieldCheck size={15}/> What leaves your workspace</summary><p>Only a general financial topic and geography are sent to Exa. Your exact net worth, debt-to-income ratio, savings rate, income, ledger rows and identity are excluded.</p><code>{request?buildQuery(request):'Confirm this metric’s inputs to generate a public query.'}</code></details>
 {researchMessage&&<div role="status" className="research-status">{researchMessage}</div>}
 {researching&&<div className="research-status">Searching public sources. Existing cards remain visible until the new research is ready.</div>}
 <div className="research-grid">{research.map(c=><article className="research-card" key={c.url}><div className="research-card-top"><span className="pill"><Globe2 size={12}/> Primary source</span><button aria-label="Dismiss research card" onClick={()=>setResearch(research.filter(x=>x.url!==c.url))}><X size={16}/></button></div><p className="holding-tag">Based on {c.holding}</p><h3><a href={c.url} target="_blank" rel="noopener noreferrer">{c.title} <ArrowUpRight size={16}/></a></h3><blockquote>{c.excerpt}</blockquote><div className="suggestion"><strong>A point to review</strong><p>{c.suggestion}</p></div><div className="source-meta"><a href={c.url} target="_blank" rel="noopener noreferrer">{c.publisher} <ArrowUpRight size={13}/></a><p>Published: {c.published||'Not supplied by source'}</p><p>Retrieved: {new Date(c.retrieved).toLocaleString('en-MY')}</p><p>Effective date & eligibility: check the linked document</p></div><details className="fine"><summary>Public query used</summary><p>{c.query}</p></details><p className="fine">Guidance is selected using your metric status at search time. The excerpt may not answer every question; read the source in full.</p><Button size="sm" variant="outline" onClick={()=>setSaved(saved.includes(c.url)?saved.filter(u=>u!==c.url):[...saved,c.url])}><Bookmark size={14}/>{saved.includes(c.url)?'Saved for this session':'Save for review'}</Button></article>)}</div>
 {!research.length&&!researching&&<div className="research-empty"><Leaf size={28}/><h2>Turn your snapshot into a useful question.</h2><p>Choose a metric above, then search for guidance from primary sources.</p><div className="question-grid">{[['net_worth','How can I strengthen my net worth?','Review debt priorities, assets and an emergency buffer.'],['dti','How much flexibility do my debt payments leave?','Explore repayment planning and borrowing guidance.'],['savings','How can I build a sustainable savings habit?','Review contributions, income definitions and savings goals.']].map(([m,title,desc])=><button key={m} onClick={()=>setMetric(m as ResearchRequest['metric'])}><h3>{title}</h3><p>{desc}</p><ArrowRight size={17}/></button>)}</div></div>}
 <p className="context-note"><Info size={14}/> Research prompts are for review. Arus does not place trades, predict returns or determine tax eligibility.</p></TabsContent></Tabs>
 <footer><span className="footer-brand">≈ arus</span><span>Statement-based clarity. Thoughtfully in your hands.</span><span>{syncedAt?`Sheets refreshed ${new Date(syncedAt).toLocaleTimeString('en-MY')}`:'Google Sheets · Not connected'}</span></footer></main>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)closeModal();}}><DialogContent className={modal==='sheets'||modal==='coverage'?'wide-dialog':''}><DialogHeader><DialogTitle>{modal==='profile'?'Complete your financial picture':modal==='coverage'?'Statement coverage':'Connect Google Sheets'}</DialogTitle><DialogDescription>{modal==='profile'?'Confirm what your statements cannot establish. These inputs stay local and are never sent to Exa.':modal==='coverage'?'Coverage is measured only against the accounts you have imported.':'Read your consolidated ledger directly from your private spreadsheet.'}</DialogDescription></DialogHeader>
 {modal==='profile'&&<div className="form-stack"><div className="calculation"><span>From bank statements</span><strong>Assets RM {money(health.bankAssets)} · Liabilities RM {money(health.bankLiabilities)}</strong></div><p className="fine">For {monthLabel(period)}. Add only amounts not already represented in the bank balances. Zero means you have checked that none exist.</p>{Object.entries({otherAssets:'Other assets: investments, retirement, property (RM)',otherLiabilities:'Other liabilities: loans and debts not in bank balances (RM)',grossIncome:'Gross monthly income before deductions (RM)',debtPayments:'Total required monthly debt payments, including cards (RM)',savingsContributions:'New monthly savings and investment contributions (RM)'}).map(([key,label])=><label key={key}>{label}<Input value={profileDraft[key]||''} inputMode="decimal" onChange={e=>{setProfileDraft({...profileDraft,[key]:e.target.value});setProfileConfirmed(false);}}/></label>)}<label>Other asset and liability valuation date<Input type="date" value={profileDate} onChange={e=>{setProfileDate(e.target.value);setProfileConfirmed(false);}}/></label><p className="fine">Debt payments are the required monthly obligations, not outstanding balances or every discretionary repayment. Savings means new money set aside; exclude transfers of existing savings, market gains and borrowed money. Count each contribution once; contributions are not added to asset balances again. Gross income of zero makes both ratios unavailable.</p><label className="check-label"><Checkbox checked={profileConfirmed} onCheckedChange={v=>setProfileConfirmed(v===true)}/>I checked coverage of all my assets and liabilities, and the income, required payments and new contributions for this month</label>{profileError&&<p role="alert" className="error">{profileError}</p>}<Button onClick={saveProfile}>Confirm & recalculate</Button></div>}
 {modal==='coverage'&&<div className="form-stack"><p className="fine">Complete means the imported statement reconciles, not that every financial account or month is present. Balance-only imports cannot support cash-flow or spending totals.</p>{statements.length?statements.map(a=><div className="coverage-row" key={a.id}><div><strong>{a.bank} · {a.account}</strong><p>{monthLabel(a.period)} · As of {dateLabel(a.asOf)}</p><span className={'pill '+(reconciled(a)?'good':'warn')}>{reconciled(a)?'Reconciled':a.transactionCoverage?'Unreconciled transactions':'Balance only · Missing transactions'}</span><p className="fine">{a.sourceName}</p></div><Button variant="ghost" size="sm" onClick={()=>{setStatements(statements.filter(x=>x.id!==a.id));setProfile(p=>({...p,confirmed:false}));}} aria-label={`Remove ${a.bank} ${a.account} ${a.period}`}><X size={16}/></Button></div>):<p className="empty-text">No statements imported.</p>}<p className="fine">Pending card charges, recent payments and accounts outside these statements are unknown.</p></div>}
 {modal==='sheets'&&<div className="form-stack"><label>Google Sheets link<Input type="url" placeholder="https://docs.google.com/spreadsheets/d/…" value={sheetUrl} onChange={e=>setSheetUrl(e.target.value)}/></label><p className="fine">The connection reads only the spreadsheet configured for this private workspace. Your sheet does not need to be public. A server-side Google credential and read access are required for the first connection.</p><Button disabled={syncing||!sheetUrl} onClick={syncSheet}><RefreshCw size={15} className={syncing?'spin':''}/>{syncing?'Updating from Google Sheets…':'Read Google Sheets'}</Button>{syncError&&<p className="error" role="alert">{syncError}</p>}<details><summary>Expected ledger structure</summary><p className="fine">Two tabs: Statements and Transactions. Statement dates and closing balances support the cash snapshot; signed transaction rows support cash flow and spending. Column mapping will be matched to your sheet once you share its link.</p><a href="/sheet-schema.txt" target="_blank" className="text-button">View supported columns <ArrowUpRight size={13}/></a></details><p className="fine">During refresh, the last successful snapshot stays visible. A failed refresh never replaces your data with zeros. Financial rows are never sent to Exa.</p></div>}

 </DialogContent></Dialog></div>;
}
