import {z} from 'zod';
export const assets={cash:'MYR cash deposits',apple:'Apple Inc (NASDAQ:AAPL)',microsoft:'Microsoft Corporation (NASDAQ:MSFT)',maybank:'Malayan Banking Berhad (Bursa:1155)',vwra:'Vanguard FTSE All-World UCITS ETF (VWRA)'};
export const regions={MY:'Malaysia',US:'United States',SG:'Singapore',GB:'United Kingdom'};
export const topics={protection:'Deposit protection',rates:'Savings rate conditions',issuer:'Company developments',overlap:'Fund exposure',tax:'Tax rules to review'};
export const researchRequest=z.object({asset:z.enum(['cash','apple','microsoft','maybank','vwra']),region:z.enum(['MY','US','SG','GB']),topic:z.enum(['protection','rates','issuer','overlap','tax']),confirmed:z.literal(true)}).strict();
export type ResearchRequest=z.infer<typeof researchRequest>;
export type ResearchCard={title:string;url:string;publisher:string;excerpt:string;published:string|null;retrieved:string;holding:string;suggestion:string;query:string};
export function buildQuery(r:ResearchRequest){return `${assets[r.asset]} ${regions[r.region]} ${topics[r.topic]} official ${r.topic==='issuer'?'investor relations latest filing':r.topic==='tax'?'tax authority eligibility effective date':r.topic==='rates'?'product terms eligibility rate effective date':r.topic==='overlap'?'fund factsheet holdings date':'deposit insurer eligibility exclusions'}`;}
export const suggestions={protection:'Check whether your deposit product and institution qualify for protection. Compare the coverage rules across institutions; do not assume every cash product is insured.',rates:'Compare the base rate, promotional period, balance caps and spending requirements against your needs. Check the effective date before treating a rate as current.',issuer:'Read the issuer’s update and review whether the business risks still match your goals. A public announcement does not establish a future share-price direction.',overlap:'Review the fund’s dated holdings for exposure that overlaps with other assets you have confirmed. Holdings can change between reporting dates.',tax:'Check the rule’s effective date, jurisdiction and eligibility. Your selected geography alone does not establish your tax residence or entitlement.'};
const hosts=['pidm.gov.my','bnm.gov.my','maybank.com','maybank2u.com.my','cimb.com.my','apple.com','sec.gov','microsoft.com','vanguard.com','vanguard.co.uk','vanguard.com.au','hasil.gov.my','irs.gov','iras.gov.sg','gov.uk','mas.gov.sg','fdic.gov','sdic.org.sg','fscs.org.uk','bursamalaysia.com'];
export function parseResearch(raw:string,r:ResearchRequest):ResearchCard[]{const found:ResearchCard[]=[];for(const part of raw.split(/(?=^Title: )/m)){const title=part.match(/^Title:\s*(.+)/m)?.[1]?.trim();const url=part.match(/^URL:\s*(https:\/\/\S+)/m)?.[1];if(!title||title==='N/A'||!url)continue;try{const u=new URL(url);if(u.username||u.password||!hosts.some(h=>u.hostname===h||u.hostname.endsWith('.'+h))||found.some(c=>c.url===url))continue;const published=part.match(/^Published(?: Date)?:\s*(.+)/m)?.[1]?.trim();const body=part.split(/(?:Highlights|Text|Content):\s*/)[1]||'';const excerpt=body.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/[#*_>]/g,'').trim().split(/\s+/).slice(0,23).join(' ');if(!excerpt)continue;found.push({title,url,publisher:u.hostname,excerpt:excerpt+'…',published:published&&published!=='N/A'?published:null,retrieved:new Date().toISOString(),holding:assets[r.asset],suggestion:suggestions[r.topic],query:buildQuery(r)});}catch{continue;}}return found.slice(0,4);}
