import {z} from 'zod';
export const regions={MY:'Malaysia',US:'United States',SG:'Singapore',GB:'United Kingdom'};
export const metrics={net_worth:'Net worth',dti:'Debt-to-income',savings:'Savings rate'};
export const researchRequest=z.object({metric:z.enum(['net_worth','dti','savings']),region:z.enum(['MY','US','SG','GB']),band:z.enum(['positive','nonpositive','flexible','within_target','high','on_target','below_target']),confirmed:z.literal(true)}).strict().superRefine((r,ctx)=>{const allowed={net_worth:['positive','nonpositive'],dti:['flexible','within_target','high'],savings:['on_target','below_target']};if(!allowed[r.metric].includes(r.band))ctx.addIssue({code:'custom',message:'Metric and research topic do not match.'});});
export type ResearchRequest=z.infer<typeof researchRequest>;
export type ResearchCard={title:string;url:string;publisher:string;excerpt:string;published:string|null;retrieved:string;holding:string;suggestion:string;query:string};
const angles={positive:'maintaining positive net worth emergency fund diversified savings guidance',nonpositive:'liabilities exceeding assets debt prioritization emergency savings financial counselling',flexible:'credit card debt minimum monthly payments repayment budget',within_target:'manage monthly debt payments debt to income household budgeting',high:'high monthly debt payment burden debt counselling repayment options avoiding new borrowing',on_target:'maintaining regular savings contributions emergency fund long term savings plan',below_target:'increase regular savings contributions gross income budget expenses emergency fund'};
export function buildQuery(r:ResearchRequest){return `${regions[r.region]} ${angles[r.band]} site:mrmoneytv.com/articles/`;}
export function reviewSuggestion(r:ResearchRequest){if(r.metric==='net_worth')return r.band==='nonpositive'?'Review which liabilities drive your net worth and compare repayment priorities with keeping an emergency buffer. Check any fees and eligibility before changing a repayment plan.':'Review your emergency buffer and asset mix. Track comparable month-end snapshots before judging whether your net worth is trending upward.';if(r.metric==='dti')return r.band==='high'?'Review required monthly debt payments and essential expenses. Explore reputable debt counselling or lender options and compare total costs before changing any borrowing.':'Review how comfortably required debt payments fit alongside essential expenses and a cash buffer. A low DTI alone does not establish that more borrowing is affordable.';return r.band==='below_target'?'Review a realistic recurring savings amount after essential expenses and required debt payments. Count new contributions once and check whether source guidance uses gross or take-home income.':'Review whether regular contributions are sustainable and aligned with an emergency buffer and longer-term goals. Keep transfers between existing savings accounts out of the numerator.';}
export const primaryHosts=['mrmoneytv.com'];
export function isSelectedArticle(url:string){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&(u.hostname==='mrmoneytv.com'||u.hostname==='www.mrmoneytv.com')&&/^\/articles\/[^/]+\/?$/.test(u.pathname);}catch{return false;}}
export function articleCard(title:string,url:string,body:string,published:string|null,r:ResearchRequest):ResearchCard|null{
 if(!isSelectedArticle(url)||!title||!body.trim())return null;
 const prose=body.split('\n').filter(line=>!line.trim().startsWith('#')&&!line.includes('| Mr Money TV')&&line.trim().split(/\s+/).length>=9).join('\n');
 const clean=prose.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/[#*_>]/g,'').trim();
 const keywords=r.metric==='dti'?['minimum payment','monthly repayment','repayment','debt','carrying a balance']:r.metric==='savings'?['emergency fund','contribution','saving','budget']:['emergency fund','net worth','asset','debt','saving'];
 const sentences=clean.match(/[^.!?\n]+[.!?]?/g)||[];
 const evidence=keywords.map(k=>sentences.find(sentence=>sentence.toLowerCase().includes(k)&&sentence.trim().split(/\s+/).length>=9)?.trim()).find(Boolean);if(!evidence)return null;
 const words=evidence.split(/\s+/);const excerpt=words.slice(0,23).join(' ')+(words.length>23?'…':'');
 const prompt=/minimum payment/i.test(evidence)?'Review your card repayment schedule and the cost of carrying a balance. A low DTI does not show how long minimum payments would take to clear debt.':/emergency fund/i.test(evidence)?'Compare the article’s emergency-fund approach with your essential expenses and access needs. Its example amounts are not personalized targets.':reviewSuggestion(r);
 return {title,url,publisher:'Mr Money TV',excerpt,published:published&&published!=='N/A'?published:null,retrieved:new Date().toISOString(),holding:metrics[r.metric],suggestion:prompt,query:buildQuery(r)};
}
export function parseResearch(raw:string,r:ResearchRequest):ResearchCard[]{const found:ResearchCard[]=[];for(const part of raw.split(/(?=^Title: )/m)){const title=part.match(/^Title:\s*(.+)/m)?.[1]?.trim(),url=part.match(/^URL:\s*(https:\/\/\S+)/m)?.[1];if(!title||!url)continue;const c=articleCard(title,url,part.split(/(?:Highlights|Text|Content):\s*/)[1]||'',part.match(/^Published(?: Date)?:\s*(.+)/m)?.[1]?.trim()||null,r);if(c&&!found.some(x=>x.url===c.url))found.push(c);}return found.slice(0,3);}
export function parseSearchResults(results:{title?:string;url?:string;highlights?:string[];text?:string;publishedDate?:string}[],r:ResearchRequest){return results.map(r0=>articleCard(r0.title||'',r0.url||'',r0.text||r0.highlights?.join(' ')||'',r0.publishedDate||null,r)).filter((x):x is ResearchCard=>!!x).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).slice(0,3);}
export function parseFetchedArticle(text:string,r:ResearchRequest){const title=text.match(/^# (.+)/m)?.[1]||text.match(/^Title: (.+)/m)?.[1]||'';const url=text.match(/^URL:\s*(https:\/\/\S+)/m)?.[1]||'';const published=text.match(/^Published:\s*(.+)/m)?.[1]||null;const body=text.split(/\n\s*\n/).slice(1).join('\n\n');return articleCard(title,url,body,published,r);}
