import {z} from 'zod';
export const regions={MY:'Malaysia',US:'United States',SG:'Singapore',GB:'United Kingdom'};
export const metrics={net_worth:'Net worth',dti:'Debt-to-income',savings:'Savings rate'};
export const researchRequest=z.object({metric:z.enum(['net_worth','dti','savings']),region:z.enum(['MY','US','SG','GB']),band:z.enum(['positive','nonpositive','flexible','within_target','high','on_target','below_target']),confirmed:z.literal(true)}).strict().superRefine((r,ctx)=>{const allowed={net_worth:['positive','nonpositive'],dti:['flexible','within_target','high'],savings:['on_target','below_target']};if(!allowed[r.metric].includes(r.band))ctx.addIssue({code:'custom',message:'Metric and research topic do not match.'});});
export type ResearchRequest=z.infer<typeof researchRequest>;
export type ResearchCard={title:string;url:string;publisher:string;excerpt:string;published:string|null;retrieved:string;holding:string;suggestion:string;query:string};
const angles={positive:'maintaining positive net worth emergency fund diversified savings guidance',nonpositive:'liabilities exceeding assets debt prioritization emergency savings financial counselling',flexible:'low debt payment burden maintain emergency fund responsible borrowing',within_target:'manage monthly debt payments debt to income household budgeting',high:'high monthly debt payment burden debt counselling repayment options avoiding new borrowing',on_target:'maintaining regular savings contributions emergency fund long term savings plan',below_target:'increase regular savings contributions gross income budget expenses emergency fund'};
export function buildQuery(r:ResearchRequest){return `${regions[r.region]} ${angles[r.band]} official financial education regulator consumer guidance`;}
export function reviewSuggestion(r:ResearchRequest){if(r.metric==='net_worth')return r.band==='nonpositive'?'Review which liabilities drive your net worth and compare repayment priorities with keeping an emergency buffer. Check any fees and eligibility before changing a repayment plan.':'Review your emergency buffer and asset mix. Track comparable month-end snapshots before judging whether your net worth is trending upward.';if(r.metric==='dti')return r.band==='high'?'Review required monthly debt payments and essential expenses. Explore reputable debt counselling or lender options and compare total costs before changing any borrowing.':'Review how comfortably required debt payments fit alongside essential expenses and a cash buffer. A low DTI alone does not establish that more borrowing is affordable.';return r.band==='below_target'?'Review a realistic recurring savings amount after essential expenses and required debt payments. Count new contributions once and check whether source guidance uses gross or take-home income.':'Review whether regular contributions are sustainable and aligned with an emergency buffer and longer-term goals. Keep transfers between existing savings accounts out of the numerator.';}
export const primaryHosts=['akpk.org.my','bnm.gov.my','pidm.gov.my','sc.com.my','kwsp.gov.my','mybijakkewangan.akpk.org.my','consumerfinance.gov','consumer.gov','investor.gov','fdic.gov','moneysense.gov.sg','mas.gov.sg','cpf.gov.sg','moneyhelper.org.uk','fca.org.uk','gov.uk'];
function card(title:string,url:string,excerpt:string,published:string|null,r:ResearchRequest):ResearchCard|null{try{const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||!primaryHosts.some(h=>u.hostname===h||u.hostname.endsWith('.'+h))||!title||title==='N/A'||!excerpt)return null;return {title,url,publisher:u.hostname,excerpt:excerpt.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/[#*_>]/g,'').trim().split(/\s+/).slice(0,23).join(' ')+'…',published:published&&published!=='N/A'?published:null,retrieved:new Date().toISOString(),holding:metrics[r.metric],suggestion:reviewSuggestion(r),query:buildQuery(r)};}catch{return null;}}
export function parseResearch(raw:string,r:ResearchRequest):ResearchCard[]{const found:ResearchCard[]=[];for(const part of raw.split(/(?=^Title: )/m)){const title=part.match(/^Title:\s*(.+)/m)?.[1]?.trim(),url=part.match(/^URL:\s*(https:\/\/\S+)/m)?.[1];if(!title||!url)continue;const c=card(title,url,part.split(/(?:Highlights|Text|Content):\s*/)[1]||'',part.match(/^Published(?: Date)?:\s*(.+)/m)?.[1]?.trim()||null,r);if(c&&!found.some(x=>x.url===c.url))found.push(c);}return found.slice(0,4);}
export function parseSearchResults(results:{title?:string;url?:string;highlights?:string[];publishedDate?:string}[],r:ResearchRequest){const found:ResearchCard[]=[];for(const result of results){const c=card(result.title||'',result.url||'',result.highlights?.join(' ')||'',result.publishedDate||null,r);if(c&&!found.some(x=>x.url===c.url))found.push(c);}return found.slice(0,4);}
