import {Statement,importSchema} from './finance';
import {profileSchema} from './health';
type Cell=string|number|boolean|null;
function rows(values:Cell[][]){if(!values.length)throw new Error('The sheet tab has no header row.');const headers=values[0].map(v=>String(v??'').trim());if(new Set(headers.filter(Boolean)).size!==headers.filter(Boolean).length)throw new Error('Duplicate column headers in the sheet.');const end=values.slice(1).findIndex(row=>row.every(v=>v===null||v===''));return values.slice(1,end<0?undefined:end+1).map((row,i):Record<string,Cell>=>({row:i+2,...Object.fromEntries(headers.map((h,j)=>[h,row[j]??'']))})).filter(r=>Object.entries(r).some(([k,v])=>k!=='row'&&v!==''));}
function amount(v:unknown,label:string){const text=String(v).trim();if(!/^-?\d+(\.\d{1,2})?$/.test(text))throw new Error(`${label}: use a number in MYR, with at most two decimal places.`);const negative=text.startsWith('-'),[a,b='']=text.replace('-','').split('.');return (Number(a)*100+Number(b.padEnd(2,'0')))*(negative?-1:1);}
function date(v:unknown){if(typeof v==='number')return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return String(v);}
export function fromSheetValues(statementValues:Cell[][],transactionValues:Cell[][]):Statement[]{const sr=rows(statementValues),tr=rows(transactionValues);const required=['statement_id','bank','account','type','currency','period','as_of','opening_balance','closing_balance','transaction_coverage'];for(const h of required)if(!statementValues[0].includes(h))throw new Error(`Statements is missing the ${h} column.`);for(const h of ['statement_id','transaction_id','date','description','amount','kind','category'])if(!transactionValues[0]?.includes(h))throw new Error(`Transactions is missing the ${h} column.`);const ids=new Set(sr.map(r=>String(r.statement_id)));if(ids.size!==sr.length)throw new Error('Duplicate statement IDs. Each statement must have one row.');if(tr.some(t=>!ids.has(String(t.statement_id))))throw new Error('A transaction refers to an unknown statement ID.');const result=sr.map(r=>{const coverage=String(r.transaction_coverage).toLowerCase();if(!['true','false'].includes(coverage))throw new Error('transaction_coverage must be TRUE or FALSE.');return {id:String(r.statement_id),bank:String(r.bank),account:String(r.account),type:String(r.type),currency:String(r.currency),period:String(r.period),asOf:date(r.as_of),balancesKnown:String(r.balances_known).toLowerCase()!=='false',opening:String(r.balances_known).toLowerCase()==='false'?0:amount(r.opening_balance,`Statements row ${r.row} opening`),closing:String(r.balances_known).toLowerCase()==='false'?0:amount(r.closing_balance,`Statements row ${r.row} closing`),transactionCoverage:coverage==='true',sourceName:String(r.source||`Google Sheets · Statements row ${r.row}`),origin:String(r.origin||''),periodStart:r.period_start?date(r.period_start):undefined,periodEnd:r.period_end?date(r.period_end):undefined,minimumPayment:r.minimum_payment!==''&&r.minimum_payment!=null?amount(r.minimum_payment,'Minimum payment'):undefined,transactions:tr.filter(t=>String(t.statement_id)===String(r.statement_id)).map(t=>({id:String(t.transaction_id),date:date(t.date),description:String(t.description),amount:amount(t.amount,`Transactions row ${t.row}`),kind:String(t.kind),category:String(t.category),page:Number(t.source_page)||1,sourceRow:Number(t.row),transactionDate:t.transaction_date?date(t.transaction_date):undefined,origin:String(t.origin||r.origin||''),newContribution:t.new_contribution?amount(t.new_contribution,'Contribution'):0}))};});const parsed=importSchema.safeParse(result);if(!parsed.success)throw new Error('Sheet values do not match the ledger: check account types, MYR currency, dates, period and transaction types.');const keys=parsed.data.map(s=>[s.bank,s.account,s.type,s.period].join('|'));if(new Set(keys).size!==keys.length)throw new Error('Multiple statements for the same account and month need resolution in Sheets.');return parsed.data;}

export function fromProfileValues(values:Cell[][]){const r=rows(values)[0];if(!r)throw new Error('Profile has no monthly inputs.');const confirmed=String(r.confirmed).toLowerCase();if(!['true','false'].includes(confirmed))throw new Error('Profile confirmed must be TRUE or FALSE.');const profileAmount=(value:unknown,label:string)=>confirmed==='false'&&(value===''||value==null)?0:amount(value,label);return profileSchema.parse({period:String(r.period),asOf:date(r.as_of),otherAssets:profileAmount(r.other_assets,'Other assets'),otherLiabilities:profileAmount(r.other_liabilities,'Other liabilities'),grossIncome:profileAmount(r.gross_income,'Gross income'),debtPayments:profileAmount(r.debt_payments,'Debt payments'),savingsContributions:profileAmount(r.savings_contributions,'Savings contributions'),confirmed:confirmed==='true'});}
