import {importPKCS8,SignJWT} from 'jose';
import {fromSheetValues} from '@/lib/sheets';
export async function POST(request:Request){
 const headers={'Cache-Control':'no-store'};
 if(request.headers.get('origin')&&new URL(request.headers.get('origin')!).host!==new URL(request.url).host)return Response.json({error:'Open the connection from Arus.'},{status:403,headers});
 const id=process.env.GOOGLE_SHEET_ID,email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY;
 if(!id||!email||!key)return Response.json({error:'Google Sheets access is not configured yet. Share your sheet link with the builder so its columns and private read access can be connected. Your current dashboard is unchanged.'},{status:503,headers});
 try{const {url}=await request.json() as {url:string};const supplied=new URL(url);if(supplied.hostname!=='docs.google.com'||supplied.pathname.match(/^\/spreadsheets\/d\/([a-zA-Z0-9_-]+)/)?.[1]!==id)return Response.json({error:'This link does not match the spreadsheet configured for your workspace.'},{status:422,headers});}catch{return Response.json({error:'Enter a valid Google Sheets link.'},{status:422,headers});}
 try{const signingKey=await importPKCS8(key.replaceAll('\\n','\n'),'RS256');const jwt=await new SignJWT({scope:'https://www.googleapis.com/auth/spreadsheets.readonly'}).setProtectedHeader({alg:'RS256',typ:'JWT'}).setIssuer(email).setAudience('https://oauth2.googleapis.com/token').setIssuedAt().setExpirationTime('5m').sign(signingKey);const tokenResponse=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt}),signal:AbortSignal.timeout(15000)});if(!tokenResponse.ok)throw new Error('Google authentication failed. Check the configured read-only service account.');const token=await tokenResponse.json() as {access_token:string};const query=new URLSearchParams({valueRenderOption:'UNFORMATTED_VALUE',dateTimeRenderOption:'SERIAL_NUMBER'});query.append('ranges',"'Statements'!A1:J2001");query.append('ranges',"'Transactions'!A1:G10002");const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values:batchGet?${query}`,{headers:{Authorization:`Bearer ${token.access_token}`},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Google could not read this sheet. Check Viewer access and the Statements / Transactions tab names.');const data=await response.json() as {valueRanges?:{values?:(string|number|boolean|null)[][]}[]};if((data.valueRanges?.[0]?.values?.length||0)>2000||(data.valueRanges?.[1]?.values?.length||0)>10001)throw new Error('This sheet exceeds the prototype row limit. Narrow the ledger range before refreshing.');const statements=fromSheetValues(data.valueRanges?.[0]?.values||[],data.valueRanges?.[1]?.values||[]);return Response.json({statements,retrievedAt:new Date().toISOString()},{headers});}catch(e){return Response.json({error:e instanceof Error?e.message:'Google Sheets could not be read. The previous snapshot is unchanged.'},{status:502,headers});}
}
